### ISSUE TITLE
Bot unable to handle messages from IFTTT

### ISSUE THREAD

**Issue by ramsabari** [rolfwessels/Command.Bot#3]
Bot is unable to parse the command, when sent from IFTTT. But it works fine with normal user. 

Below exception is thrown for IFTTT messages.

```
Unable to parse message:
Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Path '', line 0, position 0.
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader)
   at Newtonsoft.Json.Linq.JObject.Parse(String json)
   at SlackConnector.Connections.Sockets.Messages.Inbound.MessageInterpreter.ParseMessageType(String json)
   at SlackConnector.Connections.Sockets.Messages.Inbound.MessageInterpreter.InterpretMessage(String json)
```

**Comment by rolfwessels** [comment]
Hi, 

If I look at the Stack trace it seems to be an issue with the SlackConnector that I use for integrating with slack. Not sure that there is much I can do on this.

I will try to find some time this week to update the nuget package. Hopefully it has been fixed already. Otherwise I would suggest posting this issue on their issues page (https://github.com/noobot/slackconnector/issues).

**Comment by rolfwessels** [comment]
Hi,

Sorry for the delay. I have updated all 3rd party tools and made a new release.

Have a look and let met know if there are any further issues.

Regards

Rolf

**Comment by ramsabari** [comment]
Sure Rolf. I'll check. Thanks alot for your support.
